/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */
import { types } from "mobx-state-tree"

/**
 * Typescript enum
 */

export enum UserHasFilter {
  newUserVerificationCode="newUserVerificationCode",
userName="userName",
userStatus="userStatus",
resetPasswordCode="resetPasswordCode",
name="name",
gender="gender",
role="role",
lastName="lastName",
createdOn="createdOn",
updatedOn="updatedOn",
countryCode="countryCode",
phoneNumber="phoneNumber",
combinePhoneNumber="combinePhoneNumber",
dateOfBirth="dateOfBirth",
active="active",
broadSpecialty="broadSpecialty",
superSpecialty="superSpecialty",
subSpecialty="subSpecialty",
designation="designation",
designationOthers="designationOthers",
workPlace="workPlace",
city="city",
medicalCouncilName="medicalCouncilName",
yearOfRegistration="yearOfRegistration",
medicalRegistrationNumber="medicalRegistrationNumber",
verifiedMedicalRegistrationNumber="verifiedMedicalRegistrationNumber",
targetedCaseLogNumber="targetedCaseLogNumber",
anaesthesiaCaseLog="anaesthesiaCaseLog",
anaesthesiaChronicPainLog="anaesthesiaChronicPainLog",
anaesthesiaCriticalCareCaseLog="anaesthesiaCriticalCareCaseLog",
orthodonticsClinicalCaseLog="orthodonticsClinicalCaseLog",
orthodonticsPreClinical="orthodonticsPreClinical",
orthopaedicsCaseLog="orthopaedicsCaseLog",
orthopaedicsProcedureLog="orthopaedicsProcedureLog",
oralMedicineAndRadiologyCaseLog="oralMedicineAndRadiologyCaseLog",
oralRadiology="oralRadiology",
academicLog="academicLog",
publicationLog="publicationLog",
adminWorkLog="adminWorkLog",
thesisLog="thesisLog",
customLog="customLog",
thesisCases="thesisCases",
customCases="customCases",
logProfile="logProfile",
imagePath="imagePath",
userFeedback="userFeedback"
}

/**
* UserHasFilter
*/
export const UserHasFilterEnumType = types.enumeration("UserHasFilter", [
        "newUserVerificationCode",
  "userName",
  "userStatus",
  "resetPasswordCode",
  "name",
  "gender",
  "role",
  "lastName",
  "createdOn",
  "updatedOn",
  "countryCode",
  "phoneNumber",
  "combinePhoneNumber",
  "dateOfBirth",
  "active",
  "broadSpecialty",
  "superSpecialty",
  "subSpecialty",
  "designation",
  "designationOthers",
  "workPlace",
  "city",
  "medicalCouncilName",
  "yearOfRegistration",
  "medicalRegistrationNumber",
  "verifiedMedicalRegistrationNumber",
  "targetedCaseLogNumber",
  "anaesthesiaCaseLog",
  "anaesthesiaChronicPainLog",
  "anaesthesiaCriticalCareCaseLog",
  "orthodonticsClinicalCaseLog",
  "orthodonticsPreClinical",
  "orthopaedicsCaseLog",
  "orthopaedicsProcedureLog",
  "oralMedicineAndRadiologyCaseLog",
  "oralRadiology",
  "academicLog",
  "publicationLog",
  "adminWorkLog",
  "thesisLog",
  "customLog",
  "thesisCases",
  "customCases",
  "logProfile",
  "imagePath",
  "userFeedback",
      ])
